/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./components/datatables/cellRendererFrameworks/ActionButtons.vue')['default']
    AdvancedFilters: typeof import('./components/datatables/header/AdvancedFilters/index.vue')['default']
    Blueprint: typeof import('./components/datatables/Blueprint.vue')['default']
    Button: typeof import('./components/datatables/cellRendererFrameworks/Button.vue')['default']
    Columns: typeof import('./components/datatables/header/Columns/index.vue')['default']
    Datatables: typeof import('./components/datatables/index.vue')['default']
    Expanded: typeof import('./components/examples/components/Expanded.vue')['default']
    Fields: typeof import('./components/datatables/header/AdvancedFilters/Fields.vue')['default']
    Header: typeof import('./components/datatables/header/index.vue')['default']
    Link: typeof import('./components/datatables/cellRendererFrameworks/Link.vue')['default']
    Options: typeof import('./components/datatables/header/Options.vue')['default']
    RefreshTable: typeof import('./components/datatables/header/RefreshTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/datatables/header/Search.vue')['default']
    Selected: typeof import('./components/datatables/header/AdvancedFilters/Selected.vue')['default']
    Table: typeof import('./components/datatables/Table.vue')['default']
    TableServer: typeof import('./components/datatables/TableServer.vue')['default']
  }
}
