/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Datatables: typeof import('./components/datatables/index.vue')['default']
    DatatablesBlueprint: typeof import('./components/datatables/Blueprint.vue')['default']
    DatatablesCellRendererFrameworksActionButtons: typeof import('./components/datatables/cellRendererFrameworks/ActionButtons.vue')['default']
    DatatablesCellRendererFrameworksButton: typeof import('./components/datatables/cellRendererFrameworks/Button.vue')['default']
    DatatablesCellRendererFrameworksLink: typeof import('./components/datatables/cellRendererFrameworks/Link.vue')['default']
    DatatablesHeader: typeof import('./components/datatables/header/index.vue')['default']
    DatatablesHeaderAdvancedFilters: typeof import('./components/datatables/header/AdvancedFilters/index.vue')['default']
    DatatablesHeaderAdvancedFiltersFields: typeof import('./components/datatables/header/AdvancedFilters/fields/index.vue')['default']
    DatatablesHeaderAdvancedFiltersFieldsComponentsComparison: typeof import('./components/datatables/header/AdvancedFilters/fields/components/Comparison.vue')['default']
    DatatablesHeaderAdvancedFiltersFieldsComponentsDatepicker: typeof import('./components/datatables/header/AdvancedFilters/fields/components/Datepicker.vue')['default']
    DatatablesHeaderAdvancedFiltersSelected: typeof import('./components/datatables/header/AdvancedFilters/Selected.vue')['default']
    DatatablesHeaderColumns: typeof import('./components/datatables/header/Columns/index.vue')['default']
    DatatablesHeaderDownload: typeof import('./components/datatables/header/Download.vue')['default']
    DatatablesHeaderHardFilters: typeof import('./components/datatables/header/HardFilters/index.vue')['default']
    DatatablesHeaderHardFiltersSelected: typeof import('./components/datatables/header/HardFilters/Selected.vue')['default']
    DatatablesHeaderOptions: typeof import('./components/datatables/header/Options.vue')['default']
    DatatablesHeaderRefreshTable: typeof import('./components/datatables/header/RefreshTable.vue')['default']
    DatatablesHeaderSearch: typeof import('./components/datatables/header/Search.vue')['default']
    DatatablesTable: typeof import('./components/datatables/Table.vue')['default']
    DatatablesTableServer: typeof import('./components/datatables/TableServer.vue')['default']
    ExamplesComponentsCellDemo: typeof import('./components/examples/components/CellDemo.vue')['default']
    ExamplesComponentsExpanded: typeof import('./components/examples/components/Expanded.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
